apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
 DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these labels are expense resources
  labels:
    app: backend
    tier: backend
    project: expense
spec:
# modify replicas according to your case
  replicas: 1
  selector:
  # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
     app: backend
     tier: backend
     project: expense
  # pod template
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:   
      containers:
      - name: nginx
        image: ayeshacs540/backend:1.0.0
        envFrom:
        - configMapRef:
           name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec: 
  selector: #labels arre used as selectors
        app: backend
        tier: backend
        project: expense 
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port number